# Robot joint limits configuration for Staubli TX2-60L
joint_limits:
  joint_1:
    has_position_limits: true
    min_position: !degrees -180.0
    max_position: !degrees 180.0
    max_velocity: 1.0
    has_effort_limits: false
  joint_2:
    has_position_limits: true
    min_position: !degrees -127.0
    max_position: !degrees 127.0
    max_velocity: 1.0
    has_effort_limits: false
  joint_3:
    min_position: !degrees -150.0
    max_position: !degrees 150.0
    max_velocity: 1.0
    has_effort_limits: false
  joint_4:
    min_position: !degrees -270.0
    max_position: !degrees 270.0
    max_velocity: 1.0
    has_effort_limits: false
  joint_5:
    min_position: !degrees -120.0
    max_position: !degrees 120.0
    max_velocity: 1.0
    has_effort_limits: false
  joint_6:
    min_position: !degrees -270.0
    max_position: !degrees 270.0
    max_velocity: 1.0
    has_effort_limits: false
